name: Repository Dispatch
on:
  repository_dispatch:
    types: [create-pull-request]
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: create-pull-request
          # client-payload: '{"handle": "${{ github.handle }}", "type": "${{ github.type }}", "handle": "${{ github.title }}", "description": "${{ github.description }}", "targeting": "${{ github.targeting }}", "published_at": "${{ github.published_at }}"}'
          client-payload: '{"handle": "${{ handle }}"}'
      - uses: actions/checkout@v2
      - name: Create notification
        env:
          HANDLE_VAR: ${{ github.event.client_payload.handle }}
          TYPE_VAR: ${{ github.event.client_payload.type }}
          TITLE_VAR: ${{ github.event.client_payload.title }}
          DESCRIPTION_VAR: ${{ github.event.client_payload.description }}
          TARGETING_VAR: ${{ github.event.client_payload.targeting }}
          PUBLISHEDAT_VAR: ${{ github.event.client_payload.published_at }}
        # if: ${{ MY_VAR == undefined }}
        # run: MY_VAR = 
        run: |
          cat >> notifications.yml <<EOL
          $HANDLE_VAR
          $TYPE_VAR
          $TITLE_VAR
          $DESCRIPTION_VAR
          $TARGETING_VAR
          $PUBLISHEDAT_VAR
          EOL
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add notification
          body: |
            New report
            - Adds notifications detail to yml file

          title: 'Add notification'
          labels: automated pr
          assignees: Bardia-N
          branch: gh/notification

# curl -X POST \
#     -H "Accept: application/vnd.github.v3+json" \
#     -H "Authorization: token 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" \
#     https://api.github.com/repos/Bardia-N/ghactions/dispatches --data '{"event_type": "create-pull-request", "client_payload": { "handle": "my_handle" }}'